channels:
 - conda-forge
 - bioconda
 - r
 - defaults
dependencies:
  - bamutil=1.0.14
  - bedtools=2.27.1
  - biopython
  - bwa=0.7.12
  - cutadapt=1.15
  - freebayes=1.1.0
  - graphviz=2.38.0
  - picard=2.14
  - python=3.6.5
  - samtools=1.9
  - sra-tools=2.8.2
  - snakemake=5.3.0
  # - snakemake=5.17.0
  - pyyaml=3.11
  - pandas=0.24.1
  - parallel
  - repeatmasker=4.0.7
  - r-base=3.3.2
  - r-tidyverse
  - r-rlang=0.2.0
  - seqtk
  - vcflib=1.0.0_rc1
